# Generated by Django 5.2.17 on 2026-09-05 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('details', models.TextField()),
                ('user', models.CharField(default='Admin', max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('service', models.CharField(default='General AI Strategy', max_length=255)),
                ('budget', models.CharField(blank=True, default='Undisclosed', max_length=128)),
                ('project_brief', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Contacted', 'Contacted'), ('Closed / Won', 'Closed / Won'), ('Archived', 'Archived')], default='New', max_length=32)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=32)),
                ('source', models.CharField(default='Consultation Modal', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inquiry / Lead',
                'verbose_name_plural': 'Inquiries / Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(default='Confidential Client', max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('metric', models.CharField(max_length=255)),
                ('accuracy', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list, help_text='List of technology tags')),
                ('link', models.CharField(default='/case-studies', max_length=255)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Case Study',
                'verbose_name_plural': 'Portfolio Case Studies',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Engineering', max_length=128)),
                ('description', models.TextField()),
                ('bullets', models.JSONField(default=list, help_text='List of feature bullet strings')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=128)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('avatar', models.CharField(blank=True, default='', max_length=255)),
                ('skills', models.JSONField(default=list, help_text='List of technical skills')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
